/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-29 11:50:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;;

public final class add_005fingredient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String userid = "", uid = "", password = "", pass = "", managerid = "",
			clerkid = "", mid = "", cid = "", smid = "", scid = "", log = "",
			mlog = "", clog = "", reg = "";

	String item = "", item_name = "", item_code = "", item_category = "",
			item_price1 = "", ingredients = "", date_added = "";
	String ingredient = "", ingredient_name = "", ingredient_code = "",
			ingredient_category = "";

	String ingredient_price1 = "", quantity1 = "", item_slno1 = "",
			ingredient_slno1 = "", update_ingredient = "",
			delete_ingredient = "", update_item = "", delete_item = "";

	String booking = "", date = "", name = "", items = "", time = "",
			catagory = "", phone = "", booking_slno1 = "", change_status = "";
	String amount = "", type = "", show = "", draw = "", ing_quantity1 = "",
			prepare = "", deliver = "", order_type = "", item_status = "",
			status = "";

	int x = 0, slno = 0, item_slno = 0, ingredient_slno = 0, booking_slno = 0,
			count = 0, totalcount = 0, todaycount = 0;

	double item_price = 0.0, ingredient_price = 0.0, quantity = 0.0,
			ing_quantity = 0.0;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/./system_date_time.jsp", Long.valueOf(1390863956159L));
    _jspx_dependants.put("/include/common.jsp", Long.valueOf(1390867590765L));
    _jspx_dependants.put("/include/./database.jsp", Long.valueOf(1390866883554L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	
	String url = "jdbc:sqlserver://localhost:1433;databaseName=GameOfThrones;user=mehmet;password=1234567";
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	Connection con = DriverManager.getConnection(url);

	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	Statement stmt2 = con.createStatement();
	Statement stmt3 = con.createStatement();
	Statement stmt4 = con.createStatement();
	Statement stmt5 = con.createStatement();

	ResultSet rs, rs1, rs2, rs3, rs4, rs5;

	PreparedStatement pstmt, pstmt1, pstmt2, pstmt3, pstmt4, pstmt5;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	java.util.GregorianCalendar calendar = new java.util.GregorianCalendar();

	// Calendar'dan gun,ay ve saat degerleri alÄ±nÄ±p degiskene atÄ±ldÄ±. 
	String current_time = "" + calendar.get(java.util.Calendar.HOUR_OF_DAY); 
	current_time = current_time + ":" + calendar.get(java.util.Calendar.MINUTE);
	current_time = current_time + ":" + calendar.get(java.util.Calendar.SECOND);

	int hr = calendar.get(java.util.Calendar.HOUR);
	if (hr == 0)
		hr = 12;
	String mytime = "" + hr;

	int min = calendar.get(java.util.Calendar.MINUTE);
	int sec = calendar.get(java.util.Calendar.SECOND);
	String min1 = "", sec1 = "";
	if (min < 10)
		min1 = "0";
	if (sec < 10)
		sec1 = "0";
	mytime = mytime + ":" + min1 + min + ":" + sec1 + sec;

	int ampm = calendar.get(java.util.Calendar.AM_PM);
	String ap = "AM";
	if (ampm == 1)
		ap = "PM";
	mytime = mytime + ap;
	//System.out.println("mytime="+mytime+""+ap);

	String current_date = "" + calendar.get(java.util.Calendar.YEAR);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.MONTH);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.DATE);
	String[] ar = current_date.split("-");
	int current_month = calendar.get(java.util.Calendar.MONTH);
		
	String dd = ar[2];
	String mm = ar[1];
	String yy = ar[0];

	int m = Integer.parseInt(mm);
	int m1 = m + 1;

	String system_date = yy + "-" + m1 + "-" + dd;

	String a[] = { "Jan", "Feb", "Mar", "Apr", "May", "June", "July",
			"Aug", "Sept", "Oct", "Nov", "Dec" };

	//String day[]={"1st","2nd","3rd","4th","5th","6th","7th","8th","9th","0th"}; 

	String mydate = dd + " " + a[m1] + " " + yy;
	current_month = current_month + 1;

	//------------------------------- 
	//String myDate="1 Jan 2008";
	//String myString = java.text.DateFormat.getDateInstance().format(myDate);
	//java.text.DateFormat df = java.text.DateFormat.getDateInstance(DateFormat.LONG, Locale.FRANCE);
	//System.out.println("df="+df);

	//------------------------------------

	//out.println("current_time="+current_time);
	//out.println("system_date="+system_date);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"images/style.css\" type=\"text/css\"\r\n");
      out.write("\tcharset=\"utf-8\" />\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction validate(ingredient) {\r\n");
      out.write("\t\tif (ingredient.ingredient_code.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"Please enter code!\");\r\n");
      out.write("\t\t\tingredient.ingredient_code.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (ingredient.ingredient_name.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"Please enter Name!\");\r\n");
      out.write("\t\t\tingredient.ingredient_name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (ingredient.ingredient_category.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"Please enter category!\");\r\n");
      out.write("\t\t\tingredient.ingredient_category.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (ingredient.ingredient_price.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"Please enter price!\");\r\n");
      out.write("\t\t\tingredient.ingredient_price.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (ingredient.quantity.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"Please enter quantity!\");\r\n");
      out.write("\t\t\tingredient.quantity.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2>ADD INGREDIENTS</h2>\r\n");
      out.write("\t<form name=\"ingredient\" id=\"ingredient\" action=\"db_add_ingredient.jsp\"\r\n");
      out.write("\t\tmethod=\"post\" onsubmit=\"return validate(this)\">\r\n");
      out.write("\t\t<table width=\"332\" height=\"252\" border=\"0\" align=\"center\"\r\n");
      out.write("\t\t\tcellpadding=\"2\" cellspacing=\"2\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th height=\"33\" colspan=\"2\"><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");

							ingredient = (String) session.getAttribute("ingredient");
							session.removeAttribute("ingredient");
							if (ingredient != null)
								out.print(ingredient);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</div></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Ingredient Code</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"ingredient_code\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"ingredient_code\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Ingredient Name</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"ingredient_name\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"ingredient_name\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Ingredient Category</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"ingredient_category\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"ingredient_category\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Ingredient Price</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"ingredient_price\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"ingredient_price\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>quantity</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"quantity\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"quantity\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"submission\" colspan=\"2\"><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"s\" type=\"submit\" class=\"button\" value=\"ADD\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"Reset\" type=\"reset\" class=\"button\" value=\"RESET\" />\r\n");
      out.write("\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"submission\" colspan=\"2\"><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"view_ingredients.jsp\">View Ingredients</a>\r\n");
      out.write("\t\t\t\t\t</div></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
