/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-30 19:53:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;;

public final class db_005fsalata_005fekle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/./system_date_time.jsp", Long.valueOf(1390863956159L));
    _jspx_dependants.put("/include/common.jsp", Long.valueOf(1391040246577L));
    _jspx_dependants.put("/include/./database.jsp", Long.valueOf(1390919848595L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	
	String url = "jdbc:sqlserver://localhost:1433;databaseName=YemekSepeti;user=mehmet;password=1234567";
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	Connection con = DriverManager.getConnection(url);

	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	Statement stmt2 = con.createStatement();
	Statement stmt3 = con.createStatement();
	Statement stmt4 = con.createStatement();
	Statement stmt5 = con.createStatement();

	ResultSet rs, rs1, rs2, rs3, rs4, rs5;

	PreparedStatement pstmt, pstmt1, pstmt2, pstmt3, pstmt4, pstmt5;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	java.util.GregorianCalendar calendar = new java.util.GregorianCalendar();

	// Calendar'dan gun,ay ve saat degerleri alÄ±nÄ±p degiskene atÄ±ldÄ±. 
	String current_time = "" + calendar.get(java.util.Calendar.HOUR_OF_DAY); 
	current_time = current_time + ":" + calendar.get(java.util.Calendar.MINUTE);
	current_time = current_time + ":" + calendar.get(java.util.Calendar.SECOND);

	int hr = calendar.get(java.util.Calendar.HOUR);
	if (hr == 0)
		hr = 12;
	String mytime = "" + hr;

	int min = calendar.get(java.util.Calendar.MINUTE);
	int sec = calendar.get(java.util.Calendar.SECOND);
	String min1 = "", sec1 = "";
	if (min < 10)
		min1 = "0";
	if (sec < 10)
		sec1 = "0";
	mytime = mytime + ":" + min1 + min + ":" + sec1 + sec;

	int ampm = calendar.get(java.util.Calendar.AM_PM);
	String ap = "AM";
	if (ampm == 1)
		ap = "PM";
	mytime = mytime + ap;
	//System.out.println("mytime="+mytime+""+ap);

	String current_date = "" + calendar.get(java.util.Calendar.YEAR);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.MONTH);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.DATE);
	String[] ar = current_date.split("-");
	int current_month = calendar.get(java.util.Calendar.MONTH);
		
	String dd = ar[2];
	String mm = ar[1];
	String yy = ar[0];

	int m = Integer.parseInt(mm);
	int m1 = m + 1;

	String system_date = yy + "-" + m1 + "-" + dd;

	String a[] = { "Jan", "Feb", "Mar", "Apr", "May", "June", "July",
			"Aug", "Sept", "Oct", "Nov", "Dec" };

	//String day[]={"1st","2nd","3rd","4th","5th","6th","7th","8th","9th","0th"}; 

	String mydate = dd + " " + a[m1] + " " + yy;
	current_month = current_month + 1;

	//------------------------------- 
	//String myDate="1 Jan 2008";
	//String myString = java.text.DateFormat.getDateInstance().format(myDate);
	//java.text.DateFormat df = java.text.DateFormat.getDateInstance(DateFormat.LONG, Locale.FRANCE);
	//System.out.println("df="+df);

	//------------------------------------

	//out.println("current_time="+current_time);
	//out.println("system_date="+system_date);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String yemekAd = "", yemekFiyat1 = "", urun1 = "", yemekId1 = "", guncel_yemek = "";
	String icecekAd = "", icecekFiyat1 = "", urun2 = "", icecekId1 = "", guncel_icecek = "";
	String salataAd = "", salataFiyat1 = "", urun3 = "", salataId1 = "", guncel_salata = "";
	String tatliAd = "", tatliFiyat1 = "", urun4 = "", tatliId1 = "", guncel_tatli = "";
	String yemegi_sil = "", icecegi_sil = "", salatayi_sil = "", tatliyi_sil = "", kullanici_sil = "", urunu_sil = "";
	String Ad = "", Soyad = "", DTarih = "", Adres = "", EPosta = "", guncel_kullanici = "";
	String KullaniciId1 = "", Tel1 = "", Sifre1 = "", Para1 = "", KrediKartNo1 = "", Admin1 = "", kullanici = "";

	String sepet_yemek_sil ="", sepet_icecek_sil="", sepet_salata_sil="", sepet_tatli_sil=""; 
	
	int yemekId = 0, yemekFiyat = 0, icecekId = 0, icecekFiyat = 0, salataId = 0, salataFiyat = 0, tatliId = 0, tatliFiyat = 0,geneltoplam=0;
	int KullaniciId = 0, Para = 0, Admin = 0, SiparisId1 = 0;
	long Tel = 0, KrediKartNo = 0, Sifre = 0;

	String alinanyemekler = "", alinanicecekler = "", alinansalatalar = "", alinantatlilar = "";
	String yemekleradet = "", icecekleradet = "",salatalaradet="", tatlilaradet = "";
	int yemeklertoplam = 0, iceceklertoplam = 0, salatalartoplam = 0, tatlilartoplam = 0, toplamtutar = 0;
	
	String yemeklertoplam1="",iceceklertoplam1="",salatalartoplam1="",tatlilartoplam1="";
	
	String SiparisleriAl = "SiparisleriAl";

	String SiparisId = "", Yemekler = "", Icecekler = "", Salatalar = "", Tatlilar = "";

	String userid = "", uid = "", password = "", pass = "", managerid = "", clerkid = "", mid = "", cid = "", smid = "", scid = "", log = "", mlog = "", clog = "", reg = "";

	String item = "", item_name = "", item_code = "", item_category = "", item_price1 = "", ingredients = "", date_added = "";
	String ingredient = "", ingredient_name = "", ingredient_code = "", ingredient_category = "";

	String ingredient_price1 = "", quantity1 = "", item_slno1 = "", ingredient_slno1 = "", update_ingredient = "", delete_ingredient = "", update_item = "", delete_item = "";

	String booking = "", date = "", name = "", items = "", time = "", catagory = "", phone = "", booking_slno1 = "", change_status = "";
	String amount = "", type = "", show = "", draw = "", ing_quantity1 = "", prepare = "", deliver = "", order_type = "", item_status = "", status = "";

	int x = 0, slno = 0, item_slno = 0, ingredient_slno = 0, booking_slno = 0, count = 0, totalcount = 0, todaycount = 0;

	double item_price = 0.0, ingredient_price = 0.0, quantity = 0.0, ing_quantity = 0.0;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	// getParameter ile alacagÄ±mÄ±z degeri int'e atamadÄ±gÄ±mÄ±z icin String degiskene atÄ±p int olana cast ediyoruz 
	salataFiyat1 = request.getParameter("salataFiyati");
	if (salataFiyat1 != null || !"".equals(salataFiyat1))
		salataFiyat = Integer.parseInt(salataFiyat1);

	salataAd = request.getParameter("salataAdi");

	pstmt = con
			.prepareStatement("Insert into salatalar(Ad,Fiyat) values(?,?)");
	pstmt.setString(1, salataAd);
	pstmt.setInt(2, salataFiyat);
	
	pstmt.executeUpdate();

	con.close();
	session.setAttribute("salata", "salata  (" + salataAd
			+ ") basari ile eklenmistir.");
	response.sendRedirect("salata_ekle.jsp");

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
