/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-31 12:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sepetim.UyeYaz;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class GirisSayfa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	boolean newbie = true;
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie c : cookies) {
			if ((c.getName().equals("repeatVisitor"))
					&& (c.getValue().equals("yes"))) {
				newbie = false;
				break;
			}

		}
	}
	String title;
	if (newbie) {
		Cookie returnVisitorCookie = new Cookie("repeatVisitor", "yes");
		returnVisitorCookie.setMaxAge(60 * 60 * 24 * 365);
		response.addCookie(returnVisitorCookie);
		title = "Welcome Aboard";
	} else {
		title = "Welcome Back";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id='buyukdiv'>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id='girissol'>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  Giris Yaparken Uye Sorgula servlet'e gidiyor ve uye sorguluyot\r\n");
      out.write("\t\tuye var ise AnaSayfa'ya yonlendiriliyor.Yoksa Giris sayfasÄ±na yonlendiriliyor.\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t\t<form action='UyeSorgula.jsp' id='ilkLogin' method='get'>\r\n");
      out.write("\t\t\t\t<h1>GIRIS YAP</h1>\r\n");
      out.write("\t\t\t\t<input type='text' class=\"form-control\" name='username'><br>\r\n");
      out.write("\t\t\t\t<input type='password' class=\"form-control\" name='password'><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type='submit' class='btn btn-danger' value='Giris Yap'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t   <!-- Uye OL butonuna basildiginda UyeOlSayfa ya yonlendiriliyor. Uye ollmak icin bir sorun yoksa \r\n");
      out.write("\t    Uye olunuyor. varsa UyeOlSayfaya tekrar yonlendirilip hatalar donduruluyor. -->\r\n");
      out.write("\t\t\t<form action='UyeOlSayfa.jsp' id='UyeOl' method='get'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type='submit' class='btn btn-warning' value='UYE OL'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t\t\t<input type='submit' class='btn btn-warning' value='Uye Ol' > -->\r\n");
      out.write("\t\t\t");

		// UyeSorgulama sonucunda uye bulunamaz ise setAttribute ile gelen mesaj gosteriliyor. 
		// SOnra attribute remove ediliyor.
				if(session.getAttribute("uyeBilgi") != null)
					out.println((String)session.getAttribute("uyeBilgi"));
					session.removeAttribute("uyeBilgi");
					System.out.println("uye bilgi= "+session.getAttribute("uyeBilgi"));
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id='ortadakitanitim'></div>\r\n");
      out.write("\t<!--  Kullanici Cikis yapacagÄ± zaman eger admin ise admin olma ozelligini kaybetsin diye kontrol -->\r\n");
      out.write("\t");
 if(session.getAttribute("stilladmin")!=null)
		{
			session.removeAttribute("stilladmin");
		}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
