/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-28 19:34:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;;

public final class kullanicilari_005fgoruntule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/./system_date_time.jsp", Long.valueOf(1390863956159L));
    _jspx_dependants.put("/include/common.jsp", Long.valueOf(1390937562017L));
    _jspx_dependants.put("/include/./database.jsp", Long.valueOf(1390919848595L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	
	String url = "jdbc:sqlserver://localhost:1433;databaseName=YemekSepeti;user=mehmet;password=1234567";
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	Connection con = DriverManager.getConnection(url);

	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	Statement stmt2 = con.createStatement();
	Statement stmt3 = con.createStatement();
	Statement stmt4 = con.createStatement();
	Statement stmt5 = con.createStatement();

	ResultSet rs, rs1, rs2, rs3, rs4, rs5;

	PreparedStatement pstmt, pstmt1, pstmt2, pstmt3, pstmt4, pstmt5;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	java.util.GregorianCalendar calendar = new java.util.GregorianCalendar();

	// Calendar'dan gun,ay ve saat degerleri alÄ±nÄ±p degiskene atÄ±ldÄ±. 
	String current_time = "" + calendar.get(java.util.Calendar.HOUR_OF_DAY); 
	current_time = current_time + ":" + calendar.get(java.util.Calendar.MINUTE);
	current_time = current_time + ":" + calendar.get(java.util.Calendar.SECOND);

	int hr = calendar.get(java.util.Calendar.HOUR);
	if (hr == 0)
		hr = 12;
	String mytime = "" + hr;

	int min = calendar.get(java.util.Calendar.MINUTE);
	int sec = calendar.get(java.util.Calendar.SECOND);
	String min1 = "", sec1 = "";
	if (min < 10)
		min1 = "0";
	if (sec < 10)
		sec1 = "0";
	mytime = mytime + ":" + min1 + min + ":" + sec1 + sec;

	int ampm = calendar.get(java.util.Calendar.AM_PM);
	String ap = "AM";
	if (ampm == 1)
		ap = "PM";
	mytime = mytime + ap;
	//System.out.println("mytime="+mytime+""+ap);

	String current_date = "" + calendar.get(java.util.Calendar.YEAR);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.MONTH);
	current_date = current_date + "-"
			+ calendar.get(java.util.Calendar.DATE);
	String[] ar = current_date.split("-");
	int current_month = calendar.get(java.util.Calendar.MONTH);
		
	String dd = ar[2];
	String mm = ar[1];
	String yy = ar[0];

	int m = Integer.parseInt(mm);
	int m1 = m + 1;

	String system_date = yy + "-" + m1 + "-" + dd;

	String a[] = { "Jan", "Feb", "Mar", "Apr", "May", "June", "July",
			"Aug", "Sept", "Oct", "Nov", "Dec" };

	//String day[]={"1st","2nd","3rd","4th","5th","6th","7th","8th","9th","0th"}; 

	String mydate = dd + " " + a[m1] + " " + yy;
	current_month = current_month + 1;

	//------------------------------- 
	//String myDate="1 Jan 2008";
	//String myString = java.text.DateFormat.getDateInstance().format(myDate);
	//java.text.DateFormat df = java.text.DateFormat.getDateInstance(DateFormat.LONG, Locale.FRANCE);
	//System.out.println("df="+df);

	//------------------------------------

	//out.println("current_time="+current_time);
	//out.println("system_date="+system_date);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tString yemekAd = \"\", yemekFiyat1 =\"\", urun1=\"\", yemekId1=\"\",guncel_yemek=\"\";\r\n");
      out.write("\tString icecekAd = \"\", icecekFiyat1 =\"\", urun2=\"\", icecekId1=\"\",guncel_icecek=\"\";\r\n");
      out.write("\tString salataAd = \"\",salataFiyat1 =\"\", urun3 = \"\" , salataId1=\"\", guncel_salata=\"\";\r\n");
      out.write("\tString tatliAd = \"\", tatliFiyat1 = \"\",urun4 = \"\" , tatliId1=\"\",guncel_tatli=\"\";\r\n");
      out.write("\tString yemegi_sil=\"\", icecegi_sil=\"\", salatayi_sil=\"\", tatliyi_sil=\"\",Kullanici_sil=\"\";\r\n");
      out.write("\tString Ad=\"\",Soyad=\"\",DTarih=\"\",Adres=\"\",EPosta=\"\";\r\n");
      out.write("\tString KullaniciId1=\"\",DTarih1=\"\",Sifte1=\"\",Admin1=\"\",Para1=\"\",Tel1=\"\";\r\n");
      out.write("\r\n");
      out.write("\tint yemekId=0, yemekFiyat=0,icecekId=0,icecekFiyat=0,salataId=0,salataFiyat=0,tatliId=0,tatliFiyat=0;\r\n");
      out.write("\tint KullaniciId=0,Tel=0,Sifre=0,Admin=0,Para=0;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tString userid = \"\", uid = \"\", password = \"\", pass = \"\", managerid = \"\",\r\n");
      out.write("\t\t\tclerkid = \"\", mid = \"\", cid = \"\", smid = \"\", scid = \"\", log = \"\",\r\n");
      out.write("\t\t\tmlog = \"\", clog = \"\", reg = \"\";\r\n");
      out.write("\r\n");
      out.write("\tString item = \"\", item_name = \"\", item_code = \"\", item_category = \"\",\r\n");
      out.write("\t\t\titem_price1 = \"\", ingredients = \"\", date_added = \"\";\r\n");
      out.write("\tString ingredient = \"\", ingredient_name = \"\", ingredient_code = \"\",\r\n");
      out.write("\t\t\tingredient_category = \"\";\r\n");
      out.write("\r\n");
      out.write("\tString ingredient_price1 = \"\", quantity1 = \"\", item_slno1 = \"\",\r\n");
      out.write("\t\t\tingredient_slno1 = \"\", update_ingredient = \"\",\r\n");
      out.write("\t\t\tdelete_ingredient = \"\", update_item = \"\", delete_item = \"\";\r\n");
      out.write("\r\n");
      out.write("\tString booking = \"\", date = \"\", name = \"\", items = \"\", time = \"\",\r\n");
      out.write("\t\t\tcatagory = \"\", phone = \"\", booking_slno1 = \"\", change_status = \"\";\r\n");
      out.write("\tString amount = \"\", type = \"\", show = \"\", draw = \"\", ing_quantity1 = \"\",\r\n");
      out.write("\t\t\tprepare = \"\", deliver = \"\", order_type = \"\", item_status = \"\",\r\n");
      out.write("\t\t\tstatus = \"\";\r\n");
      out.write("\r\n");
      out.write("\tint x = 0, slno = 0, item_slno = 0, ingredient_slno = 0, booking_slno = 0,\r\n");
      out.write("\t\t\tcount = 0, totalcount = 0, todaycount = 0;\r\n");
      out.write("\r\n");
      out.write("\tdouble item_price = 0.0, ingredient_price = 0.0, quantity = 0.0,\r\n");
      out.write("\t\t\ting_quantity = 0.0;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction del() {\r\n");
      out.write("\t\tif (confirm(\"Yemegi silmek istediginizden emin misiniz ?\")) {\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"images/style.css\" type=\"text/css\"\r\n");
      out.write("\tcharset=\"utf-8\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		KullaniciId1 = request.getParameter("KullaniciId");
		if (KullaniciId1 != null)
			KullaniciId = Integer.parseInt(KullaniciId1);
		Kullanici_sil = request.getParameter("Kullanici_sil");

		if ("yes".equals(kullanici_sil)) {
			Ad = request.getParameter("Ad");
			x = stmt1
					.executeUpdate("Delete from kullanicilar where Id="
							+ KullaniciId);
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2>KULLANICILAR</h2>\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"736\" height=\"97\" border=\"1\">\r\n");
      out.write("\t\t");

			if (x == 1) {
		
      out.write("\r\n");
      out.write("\t\t<tr bgcolor=\"#000000\">\r\n");
      out.write("\t\t\t<th height=\"35\" colspan=\"9\"><div align=\"center\">\r\n");
      out.write("\t\t\t\t\tKullanici (");
      out.print(Ad);
      out.write(") basari ile silindi.\r\n");
      out.write("\t\t\t\t</div></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t<tr bgcolor=\"Yellow\">\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>KULLANICI ID</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>KULLANICI ADI</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>KULLANICI FIYATI (TL)</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			int icount = 0;
			rs = stmt.executeQuery("select * from kullaniciar");
			while (rs.next()) {
				Ad = rs.getString("Ad");
				Soyad = rs.getInt("Soyad");
				KullaniciId = rs.getInt("Id");
				DTarih = rs.getDate("DTarih");
				
				
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t");
      out.print(KullaniciId);
      out.write("</div></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Ad);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Soyad);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(DTarih);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Adres);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(EPosta);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Tel);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Sifre );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Admin );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(Para );
      out.write("</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"kullanici_duzenle.jsp?kullaniciId=");
      out.print(KullaniciId);
      out.write("\">Edit</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"kullanici_goruntule.jsp?yemegi_sil=yes&kullaniciId=");
      out.print(KullaniciId);
      out.write("&kullaniciAd=");
      out.print(KullaniciAd);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return del()\">Delete</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<a href=\"kullanici_ekle.jsp\">Add Ingredient</a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
