/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-31 12:22:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sepetim.TabloVerileri;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.ServletException;
import java.util.ArrayList;
import java.io.IOException;
import com.sepetim.TabloVerileri;

public final class SiparisSayfa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

public ArrayList<String> secilenYiyeceklerListesi = new ArrayList<String>();
	public ArrayList<String> secilenIceceklerListesi = new ArrayList<String>();
	public ArrayList<String> secilenTatlilarListesi = new ArrayList<String>();
	public int secilmisYemekMiktari;
	public int secilmisIcecekMiktari;
	public int secilmisTatliMiktari;

	public String yazilacak;
	public String durum;
	public String kullaniciadi;
	public String sifre;
	public static Boolean adminmi;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	TabloVerileri tb = new TabloVerileri();
	/*Admin girisinden sonra normal kullanÄ±cÄ± girislerinde de 'admin-girisi' dememesi icin konuldu.*/
	adminmi = false;

	/*SiparisleriGoster ya da KullanicilariGoster servlet'lerinden geldigimizi anlamak icin bunu kullandÄ±m.
	 * Amac : bu servlet'lerden gelindigi taktirde hala admin olmayÄ± saglamak..*/
	if (session.getAttribute("stilladmin") != null) {
		adminmi = true;
	}
	
	/*Siparis Servletine ya UyeSorgulaServlet'ten gelinebilir,Ya da UyeOlServletten.
	 * ikisinde de 'durum' isminde attiribute konulmustur.*/
	if (session.getAttribute("durum") != null) {

		durum = (String) session.getAttribute("durum");
		System.out.println("durum "+durum);
		/*Girilen durum attribute'si UyeSorgulaya ait ise kullanici ismini al.
		 */
		 
		 System.out.println("session.getAtrribute('user)'"+session.getAttribute("user"));
	
		if (durum == "UyeSorgula") {
			if (session.getAttribute("user").equals(true)) {
				adminmi = true;
				kullaniciadi = session.getAttribute("username")
						+ "-admin";
				

			}
			/*Admin ise Kulanicilari ve Siparisleri listeleyebilir.*/
			else {
				kullaniciadi = (String) session.getAttribute("username");

			}
		}
		session.setAttribute("user", false);
	}
	/*JavaScript kÄ±smÄ±nda gerekli hesap islemleri yapÄ±lmaktadÄ±r.
	 * YardÄ±mcÄ± sÄ±nÄ±f olarak ServletUtilities sÄ±nÄ±fÄ± kullanÄ±ldÄ±.(Amac tekrarlarÄ± onlemek..)*/
	 
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction temizle() {\r\n");
      out.write("\t\t\tdocument.getElementById('secilenyemeklertexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamyemeklertexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('secileniceceklertexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamiceceklertexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('secilentatlilartexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamtatlilartexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('geneltoplamtexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('secilensalatalartexti').value = '';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamsalatalartexti').value = '';\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction yemekleriYazdirma() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar e = document.getElementById('yiyeceklerkutusu');\r\n");
      out.write("\t\t\tvar secilenYemekFiyati = parseInt(e.options[e.selectedIndex].innerHTML\r\n");
      out.write("\t\t\t\t\t.replace(/[^0-9]/g, ''));\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar secilenYemek = e.options[e.selectedIndex].value.replace(\r\n");
      out.write("\t\t\t\t\t/[0-9]/g, '');\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar adet = parseInt(document.getElementById('yemekadetkutusu').value);\r\n");
      out.write("\t\t\tif (adet == '' || isNaN(adet)) {\r\n");
      out.write("\t\t\t\tadet = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('secilenyemeklertexti').value += secilenYemek\r\n");
      out.write("\t\t\t\t\t+ '(' + adet + ' adet),';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamyemeklertexti').value = +document\r\n");
      out.write("\t\t\t\t\t.getElementById('toplamyemeklertexti').value\r\n");
      out.write("\t\t\t\t\t+ (secilenYemekFiyati * adet);\r\n");
      out.write("\t\t\tvar genelToplam = parseInt(document\r\n");
      out.write("\t\t\t\t\t.getElementById('geneltoplamtexti').value);\r\n");
      out.write("\t\t\tif (!isNaN(genelToplam)) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = genelToplam\r\n");
      out.write("\t\t\t\t\t\t+ secilenYemekFiyati * adet;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = secilenYemekFiyati\r\n");
      out.write("\t\t\t\t\t\t* adet;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById('yemekadetkutusu').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction icecekleriYazdirma() {\r\n");
      out.write("\t\t\tvar e = document.getElementById('iceceklerkutusu');\r\n");
      out.write("\t\t\tsecilenIcecek = e.options[e.selectedIndex].value.replace(/[0-9]/g,\r\n");
      out.write("\t\t\t\t\t'');\r\n");
      out.write("\t\t\tvar secilenIcecekFiyati = parseInt(e.options[e.selectedIndex].innerHTML\r\n");
      out.write("\t\t\t\t\t.replace(/[^0-9]/g, ''));\r\n");
      out.write("\t\t\tvar adet = parseInt(document.getElementById('icecekadetkutusu').value);\r\n");
      out.write("\t\t\tif (adet == '' || isNaN(adet)) {\r\n");
      out.write("\t\t\t\tadet = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('secileniceceklertexti').value += secilenIcecek\r\n");
      out.write("\t\t\t\t\t+ '(' + adet + ' adet),';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamiceceklertexti').value = +document\r\n");
      out.write("\t\t\t\t\t.getElementById('toplamiceceklertexti').value\r\n");
      out.write("\t\t\t\t\t+ secilenIcecekFiyati * adet;\r\n");
      out.write("\t\t\tvar genelToplam = parseInt(document\r\n");
      out.write("\t\t\t\t\t.getElementById('geneltoplamtexti').value);\r\n");
      out.write("\t\t\tif (!isNaN(genelToplam)) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = genelToplam\r\n");
      out.write("\t\t\t\t\t\t+ secilenIcecekFiyati * adet;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = secilenIcecekFiyati\r\n");
      out.write("\t\t\t\t\t\t* adet;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('icecekadetkutusu').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction salatalariYazdirma() {\r\n");
      out.write("\t\t\tvar e = document.getElementById('salatalarkutusu');\r\n");
      out.write("\t\t\tsecilenYemek = e.options[e.selectedIndex].value.replace(/[0-9]/g,\r\n");
      out.write("\t\t\t\t\t'');\r\n");
      out.write("\t\t\tvar secilenYemekFiyati = parseInt(e.options[e.selectedIndex].innerHTML\r\n");
      out.write("\t\t\t\t\t.replace(/[^0-9]/g, ''));\r\n");
      out.write("\t\t\tvar adet = parseInt(document.getElementById('salataadetkutusu').value);\r\n");
      out.write("\t\t\tif (adet == '' || isNaN(adet)) {\r\n");
      out.write("\t\t\t\tadet = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('secilensalatalartexti').value += secilenYemek\r\n");
      out.write("\t\t\t\t\t+ '(' + adet + ' adet),';\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById('toplamsalatalartexti').value = +document\r\n");
      out.write("\t\t\t\t\t.getElementById('toplamsalatalartexti').value\r\n");
      out.write("\t\t\t\t\t+ (secilenYemekFiyati * adet);\r\n");
      out.write("\t\t\tvar genelToplam = parseInt(document\r\n");
      out.write("\t\t\t\t\t.getElementById('geneltoplamtexti').value);\r\n");
      out.write("\t\t\tif (!isNaN(genelToplam)) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = genelToplam\r\n");
      out.write("\t\t\t\t\t\t+ secilenYemekFiyati * adet;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = secilenYemekFiyati\r\n");
      out.write("\t\t\t\t\t\t* adet;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById('salataladetkutusu').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction tatlilariYazdirma() {\r\n");
      out.write("\t\t\tvar e = document.getElementById('tatlilarkutusu');\r\n");
      out.write("\t\t\tsecilenTatli = e.options[e.selectedIndex].value.replace(/[0-9]/g,\r\n");
      out.write("\t\t\t\t\t'');\r\n");
      out.write("\t\t\tvar secilenTatliFiyati = parseInt(e.options[e.selectedIndex].innerHTML\r\n");
      out.write("\t\t\t\t\t.replace(/[^0-9]/g, ''));\r\n");
      out.write("\t\t\tvar adet = parseInt(document.getElementById('tatliadetkutusu').value);\r\n");
      out.write("\t\t\tif (adet == '' || isNaN(adet)) {\r\n");
      out.write("\t\t\t\tadet = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('secilentatlilartexti').value += secilenTatli\r\n");
      out.write("\t\t\t\t\t+ '(' + adet + ' adet),';\r\n");
      out.write("\t\t\tdocument.getElementById('toplamtatlilartexti').value = +document\r\n");
      out.write("\t\t\t\t\t.getElementById('toplamtatlilartexti').value\r\n");
      out.write("\t\t\t\t\t+ secilenTatliFiyati * adet;\r\n");
      out.write("\t\t\tvar genelToplam = parseInt(document\r\n");
      out.write("\t\t\t\t\t.getElementById('geneltoplamtexti').value);\r\n");
      out.write("\t\t\tif (!isNaN(genelToplam)) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = genelToplam\r\n");
      out.write("\t\t\t\t\t\t+ secilenTatliFiyati * adet;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById('geneltoplamtexti').value = secilenTatliFiyati\r\n");
      out.write("\t\t\t\t\t\t* adet;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('tatliadetkutusu').value = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"anadiv\">\r\n");
      out.write("\t\t<div id=\"headerdiv\"></div>\r\n");
      out.write("\t\t<div id=\"ustdiv\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"SiparisSayfa.jsp\">Ana Sayfa</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://localhost:8080/YemekSiparis/Hakkimizda\">\r\n");
      out.write("\t\t\t\t\t\tHakkimizda </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://localhost:8080/YemekSiparis/Iletisim\">\r\n");
      out.write("\t\t\t\t\t\tIletisim </a></li>\r\n");
      out.write("\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\thref=\"http://localhost:8080/YemekSepetiDb/GirisSayfa.jsp\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tCikis Yap </a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			session.setAttribute("kullaniciAdi", kullaniciadi);
		
      out.write("\r\n");
      out.write("\t\t<div id=\"solparca\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				/*Ä°F ELSE bloklarÄ±nda :
				 * -Kullanicinin admin olmasÄ±na gore ,
				 * -SiparisServlet'e gelinen yere gore
				 *   Belirlemeler yapÄ±lmakta ve SayfanÄ±n sol kÄ±smÄ±n ona gore dizayn edilmektedir.*/

				if (durum == "UyeSorgula" && !adminmi) {

					System.out.println(adminmi + "adminmi");
					
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h4>HOSGELDINIZ!!</h4>\r\n");
      out.write("\t\t\t<h4>");
      out.print(kullaniciadi);
      out.write("\r\n");
      out.write("\t\t\t</h4>\r\n");
      out.write("\t\t\t<h4>SIPARISINIZI YAPINIZ</h4>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"neyiyelim\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				} else if (durum == "UyeOl") {
				
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<h3>HOSGELDINIZ ");
      out.print(session.getAttribute("AdSoyad"));
      out.write(" </h3>\r\n");
      out.write("\t\t\t\t\t<div id=\"neyiyelim\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t");
session.removeAttribute("AdSoyad");

				}

				else if (durum == "SiparisleriAl") {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h4>Secilen Yemekler Yazdirilmistir !</h4>\r\n");
      out.write("\t\t\t<div id=\"neyiyelim\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}

				else if (adminmi) {
			
      out.write("\r\n");
      out.write("\t\t\t<h5>\r\n");
      out.write("\t\t\t\t");
      out.print(kullaniciadi);
      out.write("\r\n");
      out.write("\t\t\t</h5>\r\n");
      out.write("\t\t\t<div id=\"neyiyelim\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h5>Admin Girisi</h5>\r\n");
      out.write("\t\t\t<form action='siparisleri_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='get'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='SIPARISLERI GOSTER'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form action='yiyecek_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='YEMEK ISLEMLERI'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action='icecek_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='ICECEK ISLEMLERI'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action='salata_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='SALATA ISLEMLERI'>\r\n");
      out.write("\t\t\t</form><br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action='tatli_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='TATLI ISLEMLERI'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action='kullanici_goruntule.jsp' class='btn btn-success'\r\n");
      out.write("\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t<br> <input type='submit' value='KULLANICI ISLEMLERI'>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"sagparca\">\r\n");
      out.write("\t\t<form action=\"yemek_sepetim.jsp\" method=\"get\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tr1td1\">Yiyecekler :<select multiple\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"yiyeceklerkutusu\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < tb.YiyeceklerListesi.size(); i++) {
									String yemekAd = tb.YiyeceklerListesi.get(i);
									int fiyat = tb.yemekMap.get(tb.YiyeceklerListesi.get(i));
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(yemekAd);
      out.write('"');
      out.write('>');
      out.print(yemekAd + " " + fiyat + " TL");
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								System.out.println(yemekAd + " " + fiyat + " TL");
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select><br> Adet :<input type=\"text\" name='yemekleradet'\r\n");
      out.write("\t\t\t\t\t\tid='yemekadetkutusu'>\r\n");
      out.write("\t\t\t\t\t\t<button type='button' class=\"btn btn-success\" value='tamam'\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"yemekleriYazdirma()\">Tamam</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tr1td2\">Secilen Yiyecekler : <textarea\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" rows=\"3\" name='secilenyemekler'\r\n");
      out.write("\t\t\t\t\t\t\tid='secilenyemeklertexti' width='200'></textarea> Toplam : <input\r\n");
      out.write("\t\t\t\t\t\ttype='text' name='yemektexti' id='toplamyemeklertexti'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=tr2td1>Icecekler :<select multiple\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"iceceklerkutusu\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < tb.IceceklerListesi.size(); i++) {
									String icecek = tb.IceceklerListesi.get(i);
									int fiyat = tb.icecekMap.get(tb.IceceklerListesi.get(i));
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(icecek);
      out.write('"');
      out.write('>');
      out.print(icecek + " " + fiyat + " TL");
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select><br> Adet : <input type='text' name='icecekleradet'\r\n");
      out.write("\t\t\t\t\t\tid='icecekadetkutusu'>\r\n");
      out.write("\t\t\t\t\t\t<button type='button' class='btn btn-success' value='Tamam'\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"icecekleriYazdirma()\">Tamam</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=tr2td2>Secilen Icecekler : <textarea\r\n");
      out.write("\t\t\t\t\t\t\tclass=form-control rows=3 name='secilenicecekler'\r\n");
      out.write("\t\t\t\t\t\t\tid='secileniceceklertexti'></textarea> Toplam : <input\r\n");
      out.write("\t\t\t\t\t\ttype='text' name='icecektexti' id='toplamiceceklertexti'>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=tr3td1>Salatalar : <select multiple\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"salatalarkutusu\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < tb.SalatalarListesi.size(); i++) {
									String salata = tb.SalatalarListesi.get(i);
									int fiyat = tb.salataMap.get(tb.SalatalarListesi.get(i));
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(salata);
      out.write('"');
      out.write('>');
      out.print(salata + " " + fiyat + " TL");
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select><br> Adet : <input type='text' name='salatalaradet'\r\n");
      out.write("\t\t\t\t\t\tid='salataadetkutusu'>\r\n");
      out.write("\t\t\t\t\t\t<button type='button' class='btn btn-success' value='Tamam'\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"salatalariYazdirma()\">Tamam</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=tr3td2>Secilen Salatalar : <textarea\r\n");
      out.write("\t\t\t\t\t\t\tclass=form-control name='secilensalatalar'\r\n");
      out.write("\t\t\t\t\t\t\tid='secilensalatalartexti'></textarea> Toplam : <input\r\n");
      out.write("\t\t\t\t\t\ttype='text' name='salatatexti' id='toplamsalatalartexti'>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=tr3td1>Tatlilar : <select multiple\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"tatlilarkutusu\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < tb.TatlilarListesi.size(); i++) {
									String tatli = tb.TatlilarListesi.get(i);
									int fiyat = tb.tatliMap.get(tb.TatlilarListesi.get(i));
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(tatli);
      out.write('"');
      out.write('>');
      out.print(tatli + " " + fiyat + " TL");
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select> <br> Adet : <input type='text' name='tatlilaradet'\r\n");
      out.write("\t\t\t\t\t\tid='tatliadetkutusu'>\r\n");
      out.write("\t\t\t\t\t\t<button type='button' class='btn btn-success' value='Tamam'\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"tatlilariYazdirma()\">Tamam</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=tr3td2>Secilen Tatlilar : <textarea\r\n");
      out.write("\t\t\t\t\t\t\tclass=form-control name='secilentatlilar'\r\n");
      out.write("\t\t\t\t\t\t\tid='secilentatlilartexti'></textarea> Toplam : <input type='text'\r\n");
      out.write("\t\t\t\t\t\tname='tatlitexti' id='toplamtatlilartexti'>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Toplam Tutar : <input type='text' name='geneltoplam'\r\n");
      out.write("\t\t\t\t\t\tid='geneltoplamtexti'>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type='button' class='btn btn-success' value='Temizle'\r\n");
      out.write("\t\t\t\t\t\t\tonclick='temizle()'>Temizle</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- Siparisi Onaylar ise Siparis'i yazdirmak icin\r\n");
      out.write("\t\t\t\t\t\tSiparisleriAl servlet'ine gidiliyor. -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td colspan=2><input type='submit' class='btn btn-success'\r\n");
      out.write("\t\t\t\t\t\tvalue='Siparisi Onayla'></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=altparca>Copyright Â© McanMurat</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
