/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-31 18:57:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sepetim.UyeYaz;
import java.util.*;
import java.sql.*;;

public final class UyeOl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String sonNot = "";
	String[] illegalKarakter;
	boolean uyeOlabilir = true;
		String Tel1;
	String Sifre1;
	String SifreTekrar1;
	String KrediKartNo1;
	long Tel = 0;
	long Sifre = 0 ;
	long SifreTekrar = 0;
	long KrediKartNo = 0;
	
// 	Sifre1 =  request.getParameter("sifre");
// 	SifreTekrar1 = request.getParameter("sifreTekrar");
// 	KrediKartNo1 =  request.getParameter("KrediKartNo");

	String Ad = (request.getParameter("ad") == "") ? "" : (request.getParameter("ad"));
	String Soyad = (request.getParameter("soyad") == "") ? "" : (request.getParameter("soyad"));
	String DogumTarih = (request.getParameter("dogumTarih") == "") ? "" : (request.getParameter("dogumTarih"));
	String EPosta = (request.getParameter("ePosta") == "") ? "" : (request.getParameter("ePosta"));
	String Adres = (request.getParameter("adres") == "") ? "" : (request.getParameter("adres"));
	Tel = (request.getParameter("telefon") == "") ? 0: Long.parseLong(request.getParameter("telefon"));
	Sifre = (request.getParameter("sifre") == "") ? 0 : Long.parseLong(request.getParameter("sifre"));
	SifreTekrar = (request.getParameter("sifreTekrar") ==  "") ? 0 : Long.parseLong(request.getParameter("sifreTekrar"));
	KrediKartNo = (request.getParameter("KrediKartNo") == "") ? 0 : Long.parseLong(request.getParameter("KrediKartNo"));

	

	sonNot = "";
	
	if (Ad.isEmpty() || Soyad.isEmpty() || Tel ==0
			|| EPosta.isEmpty() || Adres.isEmpty() || Sifre==0
			|| SifreTekrar==0 || KrediKartNo ==0) {
		System.out.println("Hepsi bos birader ! ");
		sonNot = "<h3 id='h3'> HIC BIR ALAN BOS BIRAKILMAMALIDIR !</h3> \n";
		uyeOlabilir = false;

	}

	/* Girilen kullanici isminde bir kullanici mevcut ise uyarÄ±lÄ±r. */
	if (new com.sepetim.UyeAra(Ad).uyeVarmi()) {

		sonNot += "<h3 id='h3'>GIRILEN KULLANICI ADI KULLANILMAKTADIR ! !</h3>";
		uyeOlabilir = false;
	}
	/* Karakter sorgulamasÄ± */
	if (Ad.split("[~#@*+%{}<>\\[\\]|\"\\_^]", 2).length > 1) {
		sonNot += "KULLANICI ISMI ICIN YANLIS KARAKTER GIRDINIZ ! \n"
				+ "[~#@*+%{}<>\\[\\]|\"\\_^] KARAKTERLERINDEN HERHANGI BIRISI KULLANILAMAZ !";
		uyeOlabilir = false;
	}
	/* Sifrelerin eslesip eslememe sorgusu */
	if (Sifre != SifreTekrar) {

		sonNot += "<h3 id='h3'> SIFRELER ESLESMIYOR !</h3>";
		uyeOlabilir = false;

	}

	// uye olamaz olarak belirlenmis ise (degiskenle) UyeOlSayfa.jsp'ye yondendirip hata mesajÄ±nÄ± gosteriyorum
	if (uyeOlabilir == false) {
		System.out.println("Son not= " + sonNot);
		session.setAttribute("sonNot", sonNot);
		response.sendRedirect("UyeOlSayfa.jsp");

	}
	System.out.println("uyeOlabilir durumu= " + uyeOlabilir);
	/* Sorun yok ise , girilen isimler kullanicilar.txt'e yazilir. */
	if (uyeOlabilir == true) {

	// uye olmada sorun varsa kullanÄ±cya uye olmada sorun olustu mesajÄ±
		try {
			new com.sepetim.UyeYaz(Ad, Soyad, DogumTarih, Tel,
					EPosta, Adres, Sifre, KrediKartNo);
		} catch (Exception ex) {
			System.out.println("UYE OLMADA SORUN");
		}

		sonNot += "<h3 id='h3'>Uye oldun hadi hayirli olsun !</h3>";
		
		// uye olmada sorun yok ise IsÄ±m bilgilerini Attribute ile gonderiyorum.
		session.setAttribute("durum", "UyeOl");
		session.setAttribute("AdSoyad", Ad + " " + Soyad);
		response.sendRedirect("SiparisSayfa.jsp");

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
