/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-01-31 13:06:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sepetim.SiparisleriYazdir;
import java.io.IOException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import java.util.*;
import java.sql.*;;

public final class yemek_005fsepetim_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/common.jsp", Long.valueOf(1391171880204L));
    _jspx_dependants.put("/include/./database.jsp", Long.valueOf(1390919848595L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	String url = "jdbc:sqlserver://localhost:1433;databaseName=YemekSepeti;user=mehmet;password=1234567";
	Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	Connection con = DriverManager.getConnection(url);

	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	Statement stmt2 = con.createStatement();
	Statement stmt3 = con.createStatement();
	Statement stmt4 = con.createStatement();
	Statement stmt5 = con.createStatement();

	ResultSet rs, rs1, rs2, rs3, rs4, rs5;

	PreparedStatement pstmt, pstmt1, pstmt2, pstmt3, pstmt4, pstmt5;

      out.write("\r\n");
      out.write("\r\n");

	String yemekAd = "", yemekFiyat1 = "", urun1 = "", yemekId1 = "", guncel_yemek = "";
	String icecekAd = "", icecekFiyat1 = "", urun2 = "", icecekId1 = "", guncel_icecek = "";
	String salataAd = "", salataFiyat1 = "", urun3 = "", salataId1 = "", guncel_salata = "";
	String tatliAd = "", tatliFiyat1 = "", urun4 = "", tatliId1 = "", guncel_tatli = "";
	String yemegi_sil = "", icecegi_sil = "", salatayi_sil = "", tatliyi_sil = "", kullanici_sil = "", urunu_sil = "";
	String Ad = "", Soyad = "", DTarih = "", Adres = "", EPosta = "", guncel_kullanici = "";
	String KullaniciId1 = "", Tel1 = "", Sifre1 = "", Para1 = "", KrediKartNo1 = "", Admin1 = "", kullanici = "";

	String sepet_yemek_sil ="", sepet_icecek_sil="", sepet_salata_sil="", sepet_tatli_sil=""; 
	String timeStamp = "";
	int yemekId = 0, yemekFiyat = 0, icecekId = 0, icecekFiyat = 0, salataId = 0, salataFiyat = 0, tatliId = 0, tatliFiyat = 0,geneltoplam=0;
	int KullaniciId = 0, Para = 0, Admin = 0, SiparisId1 = 0;
	long Tel = 0, KrediKartNo = 0, Sifre = 0;

	String alinanyemekler = "", alinanicecekler = "", alinansalatalar = "", alinantatlilar = "";
	String yemekleradet = "", icecekleradet = "",salatalaradet="", tatlilaradet = "";
	int yemeklertoplam = 0, iceceklertoplam = 0, salatalartoplam = 0, tatlilartoplam = 0, toplamtutar = 0;
	
	String yemeklertoplam1="",iceceklertoplam1="",salatalartoplam1="",tatlilartoplam1="";
	
	String SiparisleriAl = "SiparisleriAl";

	String SiparisId = "", Yemekler = "", Icecekler = "", Salatalar = "", Tatlilar = "";

	int x=0;

	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Food Online</title>\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		if (request.getParameter("secilenyemekler") != null
				|| request.getParameter("yemektexti") != null) {

			session.setAttribute("secilenyemekler",
					request.getParameter("secilenyemekler"));
			session.setAttribute("yemeklertoplam",
					request.getParameter("yemektexti"));
		}
		if (request.getParameter("secilenicecekler") != null
				|| request.getParameter("icecektexti") != null) {
	System.out.println("request.getParameter(\"icecektexti\")" + request.getParameter("icecektexti"));
			session.setAttribute("secilenicecekler",
					request.getParameter("secilenicecekler"));
			session.setAttribute("iceceklertoplam",
					request.getParameter("icecektexti"));
		}
		if (request.getParameter("secilensalatalar") != null
				|| request.getParameter("salatatexti") != null) {

			session.setAttribute("secilensalatalar",
					request.getParameter("secilensalatalar"));
			session.setAttribute("salatalartoplam",
					request.getParameter("salatatexti"));
		}
		if (request.getParameter("secilentatlilar") != null
				|| request.getParameter("tatlitexti") != null) {

			session.setAttribute("secilentatlilar",
					request.getParameter("secilentatlilar"));
			session.setAttribute("tatlilartoplam",
					request.getParameter("tatlitexti"));
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		alinanyemekler = (String) session.getAttribute("secilenyemekler");
		yemeklertoplam1 = String.valueOf(session.getAttribute("yemeklertoplam"));
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		alinanicecekler = (String) session.getAttribute("secilenicecekler");
		iceceklertoplam1 = String.valueOf(session.getAttribute("iceceklertoplam"));
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		alinansalatalar = (String) session.getAttribute("secilensalatalar");
		salatalartoplam1 = String.valueOf(session.getAttribute("salatalartoplam"));
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		alinantatlilar = (String) session.getAttribute("secilentatlilar");
		tatlilartoplam1 = String.valueOf(session.getAttribute("tatlilartoplam"));
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		// 	SiparisleriYazdir sp = new SiparisleriYazdir();
		// 	alinanyemekler = 
		// 	alinanicecekler = request.getParameter("secilenicecekler");
		// 	alinantatlilar = request.getParameter("secilentatlilar");
		// 	alinansalatalar = request.getParameter("secilensalatalar");

		// // 	toplamtutar = Integer.valueOf(request.getParameter("geneltoplam"));

		// 	yemeklertoplam = Integer.valueOf(request.getParameter("yemektexti"));
		// 	iceceklertoplam = Integer.valueOf(request.getParameter("icecektexti"));
		// 	salatalartoplam = Integer.valueOf(request.getParameter("salatatexti"));
		// 	tatlilartoplam = Integer.valueOf(request.getParameter("tatlitexti"));

		kullanici = (String) session.getAttribute("kullaniciAdi");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t// yemegi silmek istediginizden emin misiniz sorularÄ± soruluyor ona gore silme islemi gerceklesiyor.\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction del_yemekler() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (confirm(\"Yemegi silmek istediginizden emin misiniz ?\")) {\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction del_icecekler() {\r\n");
      out.write("\t\t\tif (confirm(\"Icecegi silmek istediginizden emin misiniz ?\")) {\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction del_salatalar() {\r\n");
      out.write("\t\t\tif (confirm(\"Salatayi silmek istediginizden emin misiniz ?\")) {\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction del_tatlilar() {\r\n");
      out.write("\t\t\tif (confirm(\"Tatliyi silmek istediginizden emin misiniz ?\")) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t");
 // degerler ilk basta String olarak alinip sonra int degiskenlere  aktariliyor.
		if (yemeklertoplam1 != null)
			yemeklertoplam = Integer.parseInt(yemeklertoplam1);

		if (iceceklertoplam1 != null)
			iceceklertoplam = Integer.parseInt(iceceklertoplam1);

		if (salatalartoplam1 != null)
			salatalartoplam = Integer.parseInt(salatalartoplam1);

		if (tatlilartoplam1 != null)
			tatlilartoplam = Integer.parseInt(tatlilartoplam1);

		sepet_yemek_sil = request.getParameter("sepet_yemek_sil");

		// Yiyecek basari ile silinir ise x degiskenine sorgu sonucu olarak 1 degeri atÄ±lÄ±r.
		if ("yes".equals(sepet_yemek_sil)) {
			alinanyemekler = "";
			yemeklertoplam = 0;
			session.setAttribute("secilenyemekler", alinanyemekler);
			session.setAttribute("yemeklertoplam",
					String.valueOf(yemeklertoplam));

			sepet_yemek_sil = "no";
		}
		sepet_icecek_sil = request.getParameter("sepet_icecek_sil");

		// Yiyecek basari ile silinir ise x degiskenine sorgu sonucu olarak 1 degeri atÄ±lÄ±r.
		if ("yes".equals(sepet_icecek_sil)) {
			alinanicecekler = "";
			iceceklertoplam = 0;
			sepet_icecek_sil = "no";
			session.setAttribute("secilenicecekler", alinanicecekler);
			session.setAttribute("iceceklertoplam",
					String.valueOf(iceceklertoplam));
		}
		sepet_salata_sil = request.getParameter("sepet_salata_sil");

		// Yiyecek basari ile silinir ise x degiskenine sorgu sonucu olarak 1 degeri atÄ±lÄ±r.
		if ("yes".equals(sepet_salata_sil)) {
			alinansalatalar = "";
			salatalartoplam = 0;
			sepet_salata_sil = "no";
			session.setAttribute("secilensalatalar", alinansalatalar);
			session.setAttribute("salatalartoplam",
					String.valueOf(salatalartoplam));
		}
		sepet_tatli_sil = request.getParameter("sepet_tatli_sil");

		// Yiyecek basari ile silinir ise x degiskenine sorgu sonucu olarak 1 degeri atÄ±lÄ±r.
		if ("yes".equals(sepet_tatli_sil)) {
			alinantatlilar = "";
			tatlilartoplam = 0;
			sepet_tatli_sil = "no";
			session.setAttribute("secilentatlilar", alinantatlilar);
			session.setAttribute("tatlilartoplam",
					String.valueOf(tatlilartoplam));
		}
	
      out.write("\r\n");
      out.write("\t<div id=\"headerdiv\"></div>\r\n");
      out.write("\t\t<div id=\"ustdiv\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"SiparisSayfa.jsp\">Ana Sayfa</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://localhost:8080/YemekSiparis/Hakkimizda\">\r\n");
      out.write("\t\t\t\t\t\tHakkimizda </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://localhost:8080/YemekSiparis/Iletisim\">\r\n");
      out.write("\t\t\t\t\t\tIletisim </a></li>\r\n");
      out.write("\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\thref=\"http://localhost:8080/YemekSepetiDb/GirisSayfa.jsp\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tCikis Yap </a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<table id=\"mytable\" width=\"736\" height=\"97\" border=\"1\"\r\n");
      out.write("\t\tclass=\"table table-bordered\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr bgcolor=\"Yellow\">\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong></strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>ALDIKLARIM</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>TOPLAM FIYAT</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong></strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>YEMEKLER</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td name=\"yemekler\">");
      out.print(alinanyemekler);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(yemeklertoplam);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"yemek_sepetim.jsp?sepet_yemek_sil=yes\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return del_yemekler()\">Delete</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>ICECEKLER</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td name=\"icecekler\">");
      out.print(alinanicecekler);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(iceceklertoplam);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"yemek_sepetim.jsp?sepet_icecek_sil=yes\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return del_icecekler()\">Delete</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>SALATALAR</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td name=\"salatalar\">");
      out.print(alinansalatalar);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(salatalartoplam);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"yemek_sepetim.jsp?sepet_salata_sil=yes\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return del_salatalar()\">Delete</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<strong>TATLILAR</strong>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t<td name=\"tatlilar\">");
      out.print(alinantatlilar);
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(tatlilartoplam);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"yemek_sepetim.jsp?sepet_tatli_sil=yes\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return del_tatlilar()\">Delete</a>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			session.setAttribute("alinanyemekler", alinanyemekler);
			session.setAttribute("alinanicecekler", alinanicecekler);
			session.setAttribute("alinansalatalar", alinansalatalar);
			session.setAttribute("alinantatlilar", alinantatlilar);
			session.setAttribute("yemeklertoplam", yemeklertoplam);
			session.setAttribute("iceceklertoplam", iceceklertoplam);
			session.setAttribute("salatalartoplam", salatalartoplam);
			session.setAttribute("tatlilartoplam", tatlilartoplam);
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id='kredikart'></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"OdemeYap.jsp\">\r\n");
      out.write("\t\t<table id=\"mytable2\" border=\"1\" cellpadding=\"2\" cellspacing=\"2\"\r\n");
      out.write("\t\t\tclass=\"table table-bordered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Kredi Kart No :</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"KrediKartNo\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\tid=\"KrediKartNo\" value=\"\" class=\"form-control\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<th>Guvenlik Kodu :</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"GuvenlikKodu\" type=\"text\" class=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"GuvenlikKodu\" value=\"\" class=\"form-control\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"submit\" value=\"Odeme Yap\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-success\"></input></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

						if (session.getAttribute("odeme") != null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<br> <h3>");
      out.print(session.getAttribute("odeme"));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t");

						session.removeAttribute("odeme");
						}
					
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
